try:
    print(a)
except:
    print('Somethin went wrong')
finally:
    print("The 'try expect' is finished ")